# Generated by Django 4.0.6 on 2022-07-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('auth', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
                ('segmento', models.IntegerField()),
                ('perfil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPaterno', models.CharField(max_length=50)),
                ('apellidoMaterno', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=20)),
                ('segmento', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=20)),
                ('rfc', models.CharField(max_length=13)),
                ('tipoID', models.CharField(max_length=50)),
                ('numeroID', models.CharField(max_length=50)),
                ('cuenta', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('TDD', models.CharField(max_length=50)),
            ],
        ),
    ]
