# Generated by Django 4.0.6 on 2022-07-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesAsesores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='TDD',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
